---

- name: Run file commands
  hosts: all
  gather_facts: false

  tasks:
    - name: Create a directory
      file:
        path: /home/jmc/myfolder3
        state: directory
        owner: jmc
        group: jmc

