---

- name: Blockinfile to edit files
  gather_facts: false
  hosts: all
  vars:
    packages:
      - mysql-server
      - phpmyadmin

  tasks:
    - name: Install packages old style with explicit list
      apt:
        name: "{{ item }}"
      with_items:
        - mysql-server
        - phpmyadmin

    - name: Install packages old style using variables
      apt:
        name: "{{ item }}"
      with_items:
        - "{{ packages }}"


    - name: Install packages new style with explicit list
      apt:
        name: ['mysql-server', 'phpmyadmin']

    - name: Install packages new style using variables
      apt:
        name: "{{ packages }}"